### ISSUE TITLE
A mistake in cla_utils.rank2 docstring

### ISSUE THREAD

**Issue by frankfanff53** [comp-lin-alg/comp-lin-alg-course#10]
In the exercise file cla_utils/exercise1.py, the **docstring** of function `rank2` says that

```
Return the rank2 matrix A = u1*v2^* + u2*v2^*.
```

However, in the course website we were asked to implement a function that returns a **rank-2** matrix `A = u1*v1^* + u2*v2^*`,  as a product of 2 matrices. I hope that mistake could be fixed in template and students who accept this assignment in the future would not get confused with the difference between the docstring and instruction on course website. Would be really appreciated.

**Comment by colinjcotter** [comment]
Thank you, this was fixed but I never closed the issue!
