### ISSUE TITLE
Householder algorithm should not return anything if we are modifying in-place

### ISSUE THREAD

**Issue by connorjward** [comp-lin-alg/comp-lin-alg-course#11]
The `householder` function ([here](https://github.com/comp-lin-alg/comp-lin-alg-course/blob/master/cla_utils/exercises3.py#L4)) takes input `A` and tells us to return `R`. To me this implies that `R` should be a new object. However, the notes encourage an 'in-place' algorithm:

> We are now in a position to describe the algorithm in pseudo-code. Here it is described an “in-place” algorithm, where the successive transformations to the columns of A are implemented as replacements of the values in A. This means that we can allocate memory on the computer for A which is eventually replaced with the values for R.

I found this quite confusing. Shouldn't this function not return anything?

**Comment by colinjcotter** [comment]
I fixed this - there are pros and cons to it in the classroom but I decided to make it in-place in the end.
