### ISSUE TITLE
Problem with python tests

### ISSUE THREAD

**Issue by nodwells** [comp-lin-alg/comp-lin-alg-course#5]
I typed py.test test/test_exercises1.py in the command line in Terminal and received the error "ModuleNotFoundError: No module named 'cla_utils' ". However, when I switched to python mode and typed "import cla_utils", I did not have a problem. Any ideas? :) Just wanted to add that I did change the file structure on my computer a bit, so it is possible that I accidentally deleted or moved something.

**Comment by colinjcotter** [comment]
Please can you ask your question on the Piazza message board so that other students can benefit from the answer?
