### ISSUE TITLE
Problem with setup,py

### ISSUE THREAD

**Issue by leozhangML** [comp-lin-alg/comp-lin-alg-course#9]
When the script tries to install comp-lin-alg-course as a package, I get the error message (at) https://gist.github.com/shesturnedtheweansagainstus/575402c47923c659ce0a483b36c55e21 
However on the venv's pip list, comp-lin-alg-course does appear as a package.

**Comment by colinjcotter** [comment]
This was fixed, but I forgot to close the issue.
